import {
  Code,
  Smartphone,
  Server,
  Cloud,
  Brain,
  TrendingUp,
  Users,
  Rocket,
  Award,
  Headphones,
  Lightbulb,
  Shield,
  Clock,
  Heart,
  ArrowRight,
  ChevronDown,
  Menu,
  X,
  Mail,
  Phone,
  MapPin,
  Check,
  Star,
  ExternalLink,
} from 'lucide-react';

export const ICON_MAP = {
  code: Code,
  smartphone: Smartphone,
  server: Server,
  cloud: Cloud,
  brain: Brain,
  'trending-up': TrendingUp,
  users: Users,
  rocket: Rocket,
  award: Award,
  headphones: Headphones,
  lightbulb: Lightbulb,
  shield: Shield,
  clock: Clock,
  heart: Heart,
  'arrow-right': ArrowRight,
  'chevron-down': ChevronDown,
  menu: Menu,
  x: X,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  check: Check,
  star: Star,
  'external-link': ExternalLink,
};
